import { CategoryInfo } from './types';

export const INCIDENT_CATEGORIES: CategoryInfo[] = [
  {
    id: 'cybercrime',
    title: 'Cyber Crime & Online Fraud',
    shortDesc: 'Phishing scams, unauthorized bank withdrawals, UPI fraud, social media impersonation, extortion, or hacking.',
    iconName: 'ShieldAlert',
    bnsReferences: ['IT Act Section 66C (Identity Theft)', 'IT Act Section 66D (Cheating by Personation)', 'BNS Section 318 (Cheating)'],
    defaultRelief: 'Immediate freezing of fraudulent bank accounts/wallets, tracing IP addresses and mobile numbers used by perpetrators, and recovery of stolen funds.',
    sampleNarrative: 'On [Date] at approximately [Time], I received a fraudulent telephone call/SMS claiming to be from my bank. The perpetrator tricked me into sharing an OTP under the pretext of updating KYC. Subsequently, an unauthorized transaction of Rs. [Amount] was debited from my bank account to an unknown UPI ID/Account.',
  },
  {
    id: 'theft',
    title: 'Theft / Housebreak / Burglary',
    shortDesc: 'Stolen cash, jewelry, electronics, or personal belongings from residence, shop, or public place.',
    iconName: 'PackageMinus',
    bnsReferences: ['BNS Section 303 (Theft)', 'BNS Section 305 (Theft in dwelling house)', 'BNS Section 331 (Lurking house-trespass)'],
    defaultRelief: 'Registration of FIR under relevant sections of BNS, investigation of crime scene, collection of fingerprint/CCTV evidence, and recovery of stolen items.',
    sampleNarrative: 'On [Date] between [Start Time] and [End Time], while I was away from my residence at [Location], unknown person(s) broke open the main lock of my house and stole cash, gold jewelry, and electronic gadgets valued at approximately Rs. [Total Value].',
  },
  {
    id: 'vehicle_theft',
    title: 'Vehicle Theft / Stolen Automobile',
    shortDesc: 'Stolen motorcycle, scooter, car, bicycle, or commercial vehicle.',
    iconName: 'Car',
    bnsReferences: ['BNS Section 303(2) (Theft of Motor Vehicle)', 'BNS Section 317 (Receiving stolen property)'],
    defaultRelief: 'Registration of FIR for vehicle theft, broadcast alert across police checkpoints, verification of nearby CCTV footage, and issuance of Untraced Report if vehicle is not recovered for insurance claim.',
    sampleNarrative: 'I parked my vehicle (Make: [Vehicle Make/Model], Registration No: [Reg Number], Color: [Color]) at [Parking Location] on [Date] at around [Time]. When I returned at [Time], the vehicle was missing from the spot.',
  },
  {
    id: 'assault',
    title: 'Physical Assault & Criminal Intimidation',
    shortDesc: 'Physical violence, brawl, threats to life/property, or voluntary hurt by dangerous weapons.',
    iconName: 'AlertTriangle',
    bnsReferences: ['BNS Section 115 (Voluntarily causing hurt)', 'BNS Section 351 (Criminal Intimidation)', 'BNS Section 191 (Riot/Unlawful Assembly)'],
    defaultRelief: 'Immediate medical examination (MLC), registration of FIR against accused persons, protection to complainant and family, and arrest of culprits.',
    sampleNarrative: 'On [Date] at [Time], while I was near [Location], the accused person(s) [Name(s) / Description] verbally abused me and launched an unprovoked physical assault with sticks/fists, causing injuries on my head and arms, and threatened to kill me if I approached the police.',
  },
  {
    id: 'harassment',
    title: 'Women Safety & Stalking / Harassment',
    shortDesc: 'Outraging modesty, cyber harassment, stalking, phone harassment, or workplace intimidation.',
    iconName: 'UserX',
    bnsReferences: ['BNS Section 74 (Outraging modesty of woman)', 'BNS Section 78 (Stalking)', 'BNS Section 79 (Word/gesture intended to insult modesty of woman)'],
    defaultRelief: 'Immediate police intervention, registration of FIR, recorded statement under BNSS 183 (CrPC 164), protection from harassment, and strict action against accused.',
    sampleNarrative: 'For the past [Duration], the accused person [Name/Number/Handle] has been persistently following me, sending obscene messages, calling from multiple unknown phone numbers, and making threatening comments near my workplace/residence at [Location].',
  },
  {
    id: 'financial_fraud',
    title: 'Cheating & Financial Fraud / Breach of Trust',
    shortDesc: 'Cheque bounce, non-payment of business dues, real estate scam, investment fraud, or breach of trust.',
    iconName: 'DollarSign',
    bnsReferences: ['BNS Section 316 (Criminal breach of trust)', 'BNS Section 318 (Cheating & dishonestly inducing delivery of property)', 'BNS Section 336 (Forgery)'],
    defaultRelief: 'Investigation into fraudulent documents, seizure of forged records, freezing of suspect accounts, and recovery of defrauded funds.',
    sampleNarrative: 'The accused person [Name/Company] entered into an agreement with me on [Date] promising [Services/Investment Returns] and collected an advance amount of Rs. [Amount]. Subsequently, the accused failed to honor the contract, forged signatures, and shut down operations.',
  },
  {
    id: 'lost_document',
    title: 'Lost Document / Passport / Mobile / Wallet',
    shortDesc: 'Official document loss report for Passport, Driving License, PAN, Aadhaar, SIM card, or Mobile Phone.',
    iconName: 'FileQuestion',
    bnsReferences: ['Police Station Lost Article Report (Non-Cognizable Register / LDR)'],
    defaultRelief: 'Issuance of official Lost Article Report / NCR acknowledgement copy required for re-issuance of official documents, block IMEI number, and prevention of misuse.',
    sampleNarrative: 'I regret to report that on [Date] around [Time], while traveling from [Origin] to [Destination] via [Mode of Transport], I lost my personal wallet/bag containing my original [Document Names/Mobile Phone IMEI]. Despite thorough search, the items could not be found.',
  },
  {
    id: 'domestic',
    title: 'Domestic Incident & Matrimonial Dispute',
    shortDesc: 'Domestic violence, harassment for dowry, cruelty by spouse or in-laws.',
    iconName: 'Home',
    bnsReferences: ['BNS Section 85 (Cruelty by husband or relatives)', 'Protection of Women from Domestic Violence Act 2005'],
    defaultRelief: 'Formal recording of complaint, protection order, protection of streedhan property, and legal action under relevant provisions.',
    sampleNarrative: 'Since my marriage on [Marriage Date], my spouse [Spouse Name] and in-laws residing at [Address] have been subjecting me to physical and mental harassment, demanding additional monetary funds/property, and threatening unlawful consequences.',
  },
  {
    id: 'general',
    title: 'General Grievance / Nuisance / Trespass',
    shortDesc: 'Land encroachment, public nuisance, noise pollution, unlawful trespass, or general grievance.',
    iconName: 'FileText',
    bnsReferences: ['BNS Section 329 (Criminal Trespass)', 'BNS Section 292 (Public Nuisance)'],
    defaultRelief: 'Inspection of site by police officers, removal of unlawful encroachment, warning/legal notice to offending parties, and maintenance of law and order.',
    sampleNarrative: 'I am writing to bring to your urgent attention an incident of criminal trespass and public nuisance occurring at [Location] on [Date] involving [Accused Details] who unlawfully broke into my property boundary and endangered safety.',
  },
];
